version: '3.8'

services:

  postgres: 
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=rafael
      - POSTGRES_PASSWORD=1197122
      - POSTGRES_DB=rafael
      - DATABASE_HOST=localhost

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "rafael@rafael.com"
      PGADMIN_DEFAULT_PASSWORD: "1197122"
    ports:
      - "81:80"
    depends_on:
      - postgres